swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    post:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: Monthly transactions
      description: Get all transactions for the current month
      operationId: getTransactions
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: AccountId
          in: header
          description: Attach Account ID
          required: true
          type: string
        - name: Month
          in: query
          description: Attach current month
          required: false
          type: integer
        - name: Year
          in: query
          description: Attach current year
          required: false
          type: integer
      produces:
        - application/json    
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '404':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    post:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: Details transaction
      description: Get details of a transaction
      operationId: getTransactionById
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Attach Id transaction
          required: true
          type: string
      produces:
       - application/json  
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Invalid fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User transaction
      summary: Update transaction
      description: Update of a specific transaction
      operationId: updateTransaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Attach Id transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            type: object
            properties:
                Category:
                  type: string
                Notes:
                  type: string
      produces:
        - application/json  
      responses:
        '200':
          description: Successful operation
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Invalid fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
      type: object
      properties:
        Status:
          type: integer
          format: '0'
        Message:
          type: string
          format: User transactions retrieved successully
        Id:
          type: string
          format: int64
        Date:
          type: string
          format: date
          description: Transaction date 
        Description:
          type: string
          description: Account associated with the transaction
        Amount:
          type: number
          format: float
          description: Transaction amount
        Balance:
          type: number
          format: float
          description: Balance amount
        Transaction type:
          type: string
          description: Transaction description
        Category:
          type: string
          description: Transaction category
        Notes:
          type: string
          description: Transaction note